blank_issues_enabled: true
contact_links:
  - name: Home Assistant Community Forum
    url: https://community.home-assistant.io/
    about: Ask questions and discuss with the Home Assistant community
  - name: Tado Support
    url: https://support.tado.com/
    about: For issues with Tado hardware or service
